FROM node:18-alpine3.18

WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy app source code
COPY . .

# Build frontend assets if needed (if using a build step)
RUN npm run build

# Expose port
EXPOSE 3000

# Start the server
CMD ["npm", "start"]
